STUDENT GRADE PREDICTION ANALAYSIS

In [1]:



import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.utils import shuffle


In [2]:
#read data sets by using pandas url
dataset = 'https://raw.githubusercontent.com/amankharwal/Website-data/master/student-mat.csv'
data = pd.read_csv(dataset,na_values=['?'])

In [3]:
data.head()

school sex  age address famsize Pstatus  Medu  Fedu     Mjob      Fjob  ...  \
0     GP   F   18       U     GT3       A     4     4  at_home   teacher  ...   
1     GP   F   17       U     GT3       T     1     1  at_home     other  ...   
2     GP   F   15       U     LE3       T     1     1  at_home     other  ...   
3     GP   F   15       U     GT3       T     4     2   health  services  ...   
4     GP   F   16       U     GT3       T     3     3    other     other  ...   

  famrel freetime  goout  Dalc  Walc health absences  G1  G2  G3  
0      4        3      4     1     1      3        6   5   6   6  
1      5        3      3     1     1      3        4   5   5   6  
2      4        3      2     2     3      3       10   7   8  10  
3      3        2      2     1     1      5        2  15  14  15  
4      4        3      2     1     2      5        4   6  10  10  

[5 rows x 33 columns]

In [4]:
data = data[["G1", "G2", "G3", "studytime", "failures", "absences"]]
predict = "G3"
x = np.array(data.drop([predict], 1))
y = np.array(data[predict])

from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size=0.2)

/var/folders/qg/nqj4yjj93l154___47sr3dcc0000gn/T/ipykernel_5103/476592969.py:3: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  x = np.array(data.drop([predict], 1))


In [5]:
linear_regression = LinearRegression()
linear_regression.fit(xtrain, ytrain)
accuracy = linear_regression.score(xtest, ytest)
print(accuracy)

0.8014977143283735


In [6]:

predictions = linear_regression.predict(xtest)
for i in range(len(predictions)):
    print(predictions[x], xtest[x], [ytest[x]])

[[ 3.76353848  6.30750618 16.03424264 15.6810564   6.30750618]
 [ 3.76353848  3.76353848 16.03424264 15.6810564   9.57351233]
 [11.47939676  7.45757377 16.03424264  9.36404288  5.93684089]
 ...
 [ 5.93684089  7.45757377 -0.68274516  9.36404288  9.36404288]
 [ 9.56565051  9.15573518 -0.68274516 15.6810564  15.6810564 ]
 [ 7.45757377  3.68387663 -0.68274516 15.6810564   3.76353848]] [[[ 6  5  1  3  0]
  [ 8  7  2  0  4]
  [15 16  3  0  2]
  [16 15  3  0 16]
  [ 8  7  2  0  4]]

 [[ 6  5  1  3  0]
  [ 6  5  1  3  0]
  [15 16  3  0  2]
  [16 15  3  0 16]
  [10 10  2  0  4]]

 [[10 12  2  1  4]
  [ 7  8  2  0 12]
  [15 16  3  0  2]
  [ 9 10  2  0  2]
  [ 7  7  2  1  0]]

 ...

 [[ 7  7  2  1  0]
  [ 7  8  2  0 12]
  [ 8  0  1  0  0]
  [ 9 10  2  0  2]
  [ 9 10  2  0  2]]

 [[11 10  2  0  0]
  [ 9 10  3  0  0]
  [ 8  0  1  0  0]
  [16 15  3  0 16]
  [16 15  3  0 16]]

 [[ 7  8  2  0 12]
  [ 3  5  2  1  8]
  [ 8  0  1  0  0]
  [16 15  3  0 16]
  [ 6  5  1  3  0]]] [array([[ 0,  6, 18, 15,  6]